import { ArrowLeft, Check, Clipboard, ExternalLink } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { getComplaint, messageFromError } from '../services/api';
import { formatDate, shortAddress, transactionUrl } from '../utils/format';
import StatusBadge from '../components/StatusBadge';
import Loading from '../components/Loading';
import { useApp } from '../context/AppContext';

export default function ComplaintDetails() { const { id } = useParams(); const [complaint, setComplaint] = useState(null); const [loading, setLoading] = useState(true); const { notify } = useApp(); useEffect(() => { getComplaint(id).then((data) => setComplaint(data.complaint)).catch((error) => notify(messageFromError(error), 'error')).finally(() => setLoading(false)); }, [id]); if (loading) return <Loading label="Loading complaint" />; if (!complaint) return <div className="empty-state">Complaint could not be found.</div>; const stages = ['Pending', 'In Progress', 'Resolved']; const current = stages.indexOf(complaint.status); return <div className="stack detail-page"><Link className="back-link" to="/complaints"><ArrowLeft size={16} /> Back to complaints</Link><div className="detail-header"><div><p className="eyebrow">COMPLAINT #{String(complaint.complaintId).padStart(3, '0')}</p><h2>{complaint.title}</h2><p className="muted">Submitted {formatDate(complaint.timestamp)} by {shortAddress(complaint.complainant)}</p></div><StatusBadge status={complaint.status} /></div><div className="detail-grid"><section className="panel description-panel"><p className="eyebrow">REPORT DETAILS</p><h3>What was reported</h3><p className="description-text">{complaint.description}</p><div className="metadata"><div><span>Complainant</span><strong className="mono">{shortAddress(complaint.complainant)}</strong></div><div><span>Registered</span><strong>{formatDate(complaint.timestamp)}</strong></div></div></section><section className="panel timeline-panel"><p className="eyebrow">CASE LIFECYCLE</p><h3>Status timeline</h3><div className="timeline">{stages.map((stage, index) => <div className={index <= current ? 'timeline-step complete' : 'timeline-step'} key={stage}><div className="timeline-icon">{index <= current ? <Check size={14} /> : index + 1}</div><div><strong>{stage}</strong><span>{index === 0 ? 'Case registered' : index === 1 ? 'Team is working on it' : 'Issue marked complete'}</span></div></div>)}</div></section></div><section className="panel transaction-panel"><div><p className="eyebrow">BLOCKCHAIN RECORD</p><h3>Confirmation details</h3></div><div className="transaction-value"><span>Transaction hash</span><button onClick={() => navigator.clipboard.writeText(complaint.transactionHash)} className="hash-link">{shortAddress(complaint.transactionHash)} <Clipboard size={14} /></button><a href={transactionUrl(complaint.transactionHash)} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Explorer</a></div></section></div>; }