import { ChevronLeft, ChevronRight, ExternalLink, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { getComplaints, messageFromError, updateComplaintStatus } from '../services/api';
import { formatDate, shortAddress, transactionUrl } from '../utils/format';
import StatusBadge from '../components/StatusBadge';
import Loading from '../components/Loading';
import EmptyState from '../components/EmptyState';
import { useApp } from '../context/AppContext';

export default function Complaints({ admin = false }) {
  const [data, setData] = useState({ complaints: [], pagination: {} }); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [updating, setUpdating] = useState(null); const { notify } = useApp();
  useEffect(() => { setLoading(true); getComplaints({ search: query, status, page, limit: 8 }).then(setData).catch((error) => notify(messageFromError(error), 'error')).finally(() => setLoading(false)); }, [query, status, page]);
  async function changeStatus(item, nextStatus) { if (nextStatus === item.status || !window.confirm(`Update complaint status to ${nextStatus}?`)) return; setUpdating(item.complaintId); try { await updateComplaintStatus(item.complaintId, nextStatus); notify('Complaint status updated.'); setData({ ...data, complaints: data.complaints.map((entry) => entry.complaintId === item.complaintId ? { ...entry, status: nextStatus } : entry) }); } catch (error) { notify(messageFromError(error), 'error'); } finally { setUpdating(null); } }
  return <div className="stack"><section className="page-intro"><div><p className="eyebrow">{admin ? 'ADMINISTRATION' : 'CASE REGISTER'}</p><h2>{admin ? 'Manage complaints' : 'All complaints'}</h2><p className="muted">{admin ? 'Review the register and move cases through their lifecycle.' : 'Search, filter, and inspect every registered civic issue.'}</p></div>{!admin && <Link className="primary-button" to="/register">Register complaint</Link>}</section><div className="panel table-panel"><div className="table-toolbar"><div className="search-box"><Search size={17} /><input value={query} onChange={(event) => { setPage(1); setQuery(event.target.value); }} placeholder="Search complaints" /></div><select value={status} onChange={(event) => { setPage(1); setStatus(event.target.value); }}><option value="">All statuses</option><option>Pending</option><option>In Progress</option><option>Resolved</option></select></div>{loading ? <Loading label="Loading complaints" /> : data.complaints.length ? <><div className="table-scroll"><table><thead><tr><th>ID</th><th>Complaint</th><th>Complainant</th><th>Status</th><th>Submitted</th><th>Transaction</th><th /></tr></thead><tbody>{data.complaints.map((item) => <tr key={item.complaintId}><td className="mono">#{String(item.complaintId).padStart(3, '0')}</td><td><Link className="table-title" to={`/complaints/${item.complaintId}`}>{item.title}</Link><span className="table-subtitle">{item.description.slice(0, 52)}{item.description.length > 52 ? '...' : ''}</span></td><td className="mono">{shortAddress(item.complainant)}</td><td>{admin ? <select className="status-select" disabled={updating === item.complaintId} value={item.status} onChange={(event) => changeStatus(item, event.target.value)}><option>Pending</option><option>In Progress</option><option>Resolved</option></select> : <StatusBadge status={item.status} />}</td><td>{formatDate(item.timestamp)}</td><td>{item.transactionHash ? <a className="hash-link" href={transactionUrl(item.transactionHash)} target="_blank" rel="noreferrer">{shortAddress(item.transactionHash)} <ExternalLink size={12} /></a> : '-'}</td><td><Link className="view-link" to={`/complaints/${item.complaintId}`}>View</Link></td></tr>)}</tbody></table></div><div className="pagination"><span>{data.pagination.total || 0} total records</span><div><button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} /></button><b>Page {page} of {Math.max(data.pagination.pages || 1, 1)}</b><button disabled={page >= (data.pagination.pages || 1)} onClick={() => setPage(page + 1)}><ChevronRight size={16} /></button></div></div></> : <EmptyState />}</div></div>;
}