import { CheckCircle2, Clipboard, FilePlus2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { registerComplaint as createComplaint, messageFromError } from '../services/api';
import { useApp } from '../context/AppContext';
import { shortAddress } from '../utils/format';

export default function Register() {
  const { walletAddress, connectWallet, notify } = useApp(); const [form, setForm] = useState({ title: '', description: '', walletAddress }); const [loading, setLoading] = useState(false); const [result, setResult] = useState(null);
  function change(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function submit(event) { event.preventDefault(); setLoading(true); setResult(null); try { const data = await createComplaint({ ...form, walletAddress: form.walletAddress || walletAddress }); setResult(data); notify('Complaint registered on the blockchain.'); setForm({ title: '', description: '', walletAddress: walletAddress || '' }); } catch (error) { notify(messageFromError(error), 'error'); } finally { setLoading(false); } }
  return <div className="form-layout"><section className="page-intro"><div><p className="eyebrow">NEW CASE</p><h2>Register a complaint</h2><p className="muted">Record an issue directly on the local civic ledger.</p></div></section><div className="panel form-panel"><div className="form-heading"><div className="form-icon"><FilePlus2 size={21} /></div><div><h3>Complaint information</h3><p>Be specific so the right team can take action.</p></div></div>{result ? <div className="success-box"><CheckCircle2 size={31} /><h3>Complaint registered</h3><p>It is now confirmed on-chain and ready to track.</p><div className="result-row"><span>Complaint ID</span><strong>#{result.complaint.complaintId}</strong></div><div className="result-row"><span>Transaction</span><button onClick={() => navigator.clipboard.writeText(result.transactionHash)}>{shortAddress(result.transactionHash)} <Clipboard size={14} /></button></div><Link className="primary-button full-button" to={`/complaints/${result.complaint.complaintId}`}>View complaint</Link></div> : <form onSubmit={submit}><label>Complaint title<input name="title" maxLength="120" value={form.title} onChange={change} placeholder="e.g. Street light not working" required /></label><label>Description<textarea name="description" maxLength="1000" rows="6" value={form.description} onChange={change} placeholder="Describe the location, impact, and any useful context..." required /></label><label>Complainant wallet address<div className="input-action"><input name="walletAddress" value={form.walletAddress} onChange={change} placeholder="0x..." required pattern="0x[a-fA-F0-9]{40}" /><button type="button" onClick={connectWallet}>Use connected wallet</button></div><small>This identifies the person submitting the report. The configured server signer confirms the blockchain transaction.</small></label><button className="primary-button submit-button" disabled={loading}>{loading ? 'Submitting transaction...' : 'Submit complaint'}</button></form>}</div></div>;
}